namespace ErgastApi.Responses.Models
{
    public enum FinishingStatusId
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        Finished = 1,
        Disqualified = 2,
        Accident = 3,
        Collision = 4,
        Engine = 5,
        Gearbox = 6,
        Transmission = 7,
        Clutch = 8,
        Hydraulics = 9,
        Electrical = 10,
        /// <summary>+1 Lap</summary>
        Laps1 = 11,
        /// <summary>+2 Laps</summary>
        Laps2 = 12,
        /// <summary>+3 Laps</summary>
        Laps3 = 13,
        /// <summary>+4 Laps</summary>
        Laps4 = 14,
        /// <summary>+5 Laps</summary>
        Laps5 = 15,
        /// <summary>+6 Laps</summary>
        Laps6 = 16,
        /// <summary>+7 Laps</summary>
        Laps7 = 17,
        /// <summary>+8 Laps</summary>
        Laps8 = 18,
        /// <summary>+9 Laps</summary>
        Laps9 = 19,
        SpunOff = 20,
        Radiator = 21,
        Suspension = 22,
        Brakes = 23,
        Differential = 24,
        Overheating = 25,
        Mechanical = 26,
        Tyre = 27,
        DriverSeat = 28,
        Puncture = 29,
        Driveshaft = 30,
        Retired = 31,
        FuelPressure = 32,
        FrontWing = 33,
        WaterPressure = 34,
        Refuelling = 35,
        Wheel = 36,
        Throttle = 37,
        Steering = 38,
        Technical = 39,
        Electronics = 40,
        BrokenWing = 41,
        HeatShieldFire = 42,
        Exhaust = 43,
        OilLeak = 44,
        /// <summary>+11 Laps</summary>
        Laps11 = 45,
        WheelRim = 46,
        WaterLeak = 47,
        FuelPump = 48,
        TrackRod = 49,
        /// <summary>+17 Laps</summary>
        Laps17 = 50,
        OilPressure = 51,
        /// <summary>+13 Laps</summary>
        Laps13 = 53,
        Withdrew = 54,
        /// <summary>+12 Laps</summary>
        Laps12 = 55,
        EngineFire = 56,
        /// <summary>+26 Laps</summary>
        Laps26 = 58,
        TyrePuncture = 59,
        OutOfFuel = 60,
        WheelNut = 61,
        NotClassified = 62,
        Pneumatics = 63,
        Handling = 64,
        RearWing = 65,
        Fire = 66,
        WheelBearing = 67,
        Physical = 68,
        FuelSystem = 69,
        OilLine = 70,
        FuelRig = 71,
        LaunchControl = 72,
        Injured = 73,
        Fuel = 74,
        PowerLoss = 75,
        Vibrations = 76,
        Rule107Percent = 77,
        Safety = 78,
        Drivetrain = 79,
        Ignition = 80,
        DidNotQualify = 81,
        Injury = 82,
        Chassis = 83,
        Battery = 84,
        Stalled = 85,
        Halfshaft = 86,
        Crankshaft = 87,
        /// <summary>+10 Laps</summary>
        Laps10 = 88,
        SafetyConcerns = 89,
        NotRestarted = 90,
        Alternator = 91,
        Underweight = 92,
        SafetyBelt = 93,
        OilPump = 94,
        FuelLeak = 95,
        Excluded = 96,
        DidNotPrequalify = 97,
        Injection = 98,
        Distributor = 99,
        DriverUnwell = 100,
        Turbo = 101,
        CVJoint = 102,
        WaterPump = 103,
        FatalAccident = 104,
        SparkPlugs = 105,
        FuelPipe = 106,
        EyeInjury = 107,
        OilPipe = 108,
        Axle = 109,
        WaterPipe = 110,
        /// <summary>+14 Laps</summary>
        Laps14 = 111,
        /// <summary>+15 Laps</summary>
        Laps15 = 112,
        /// <summary>+25 Laps</summary>
        Laps25 = 113,
        /// <summary>+18 Laps</summary>
        Laps18 = 114,
        /// <summary>+22 Laps</summary>
        Laps22 = 115,
        /// <summary>+16 Laps</summary>
        Laps16 = 116,
        /// <summary>+24 Laps</summary>
        Laps24 = 117,
        /// <summary>+29 Laps</summary>
        Laps29 = 118,
        /// <summary>+23 Laps</summary>
        Laps23 = 119,
        /// <summary>+21 Laps</summary>
        Laps21 = 120,
        Magneto = 121,
        /// <summary>+44 Laps</summary>
        Laps44 = 122,
        /// <summary>+30 Laps</summary>
        Laps30 = 123,
        /// <summary>+19 Laps</summary>
        Laps19 = 124,
        /// <summary>+46 Laps</summary>
        Laps46 = 125,
        Supercharger = 126,
        /// <summary>+20 Laps</summary>
        Laps20 = 127,
        /// <summary>+42 Laps</summary>
        Laps42 = 128,
        EngineMisfire = 129,
        CollisionDamage = 130,
        PowerUnit = 131,
        ERS = 132,
        BrakeDuct = 135
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    }
}